export const WeatherActions = {
  GET_WEATHER: 'GET_WEATHER',
  GET_WEATHER_SUCCESS: 'GET_WEATHER_SUCCESS',
  GET_WEATHER_FAILURE: 'GET_WEATHER_FAILURE'
};

export const StarshipsAction = {
  GET_STARSHIPS: 'GET_STARSHIPS',
  GET_STARSHIPS_SUCCESS: 'GET_STARSHIPS_SUCCESS',
  GET_STARSHIPS_FAILURE: 'GET_STARSHIPS_FAILURE'
};

export const Starship_Detail = {
  STARSHIP_GET_DETAIL: 'STARSHIP_GET_DETAIL',
  STARSHIP_GET_DETAIL_SUCCESS: 'STARSHIP_GET_DETAIL_SUCCESS',
  STARSHIP_GET_DETAIL_FAILURE: 'STARSHIP_GET_DETAIL_FAILURE'
};
